### ISSUE TITLE
Missing stub entry for `fractions._RATIONAL_FORMAT` leads to mypy error

### ISSUE THREAD

**Issue by sr-murthy** [python/typeshed#11652]
The [stub file](https://github.com/python/typeshed/blob/main/stdlib/fractions.pyi) for the [`fractions` standard library](https://github.com/python/cpython/blob/3.12/Lib/fractions.py) is missing an entry for [`_RATIONAL_FORMAT`](https://github.com/python/cpython/blob/3.12/Lib/fractions.py), which is a compiled regular expression.

I'm using libraries which import `_RATIONAL_FORMAT`:
```python
...
from fractions import _RATIONAL_FORMAT
...
```
but running mypy against them leads to this error:
```shell
error: Module "fractions" has no attribute "_RATIONAL_FORMAT"  [attr-defined]
```
Is it not possible to add an entry for `_RATIONAL_FORMAT`? It is private, but really useful when validating numeric strings.

I saw some [relevant discussion](https://github.com/python/mypy/issues/12286) on this type of error in the mypy repo, but the solution proposed there does not work for me - it was to rewrite that particular import as an aliased import (using `as`), and setting the config. option `implicit_reexport` to `true` in `[tool.mypy]` in my project TOML. But that does not work.

My `[tool.mypy]` section in the project TOML looks like this:
```toml
[tool.mypy]
python_version = 3.12
mypy_path = "src"
namespace_packages = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
exclude = "version.py"
explicit_package_bases = true
follow_imports = "silent"
ignore_missing_imports = true
implicit_reexport = true
```
I'm using `mypy` version 1.9.0 and Python 3.11.2.
