### ISSUE TITLE
Do we need to run actions on forks?

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#7066]
Right now each my PR is tested twice: on `python/typeshed@issue-branch` and `sobolevn/typeshed@issue-branch`. Do we really want this?

<img width="1025" alt="Снимок экрана 2022-01-28 в 11 04 50" src="https://user-images.githubusercontent.com/4660275/151510186-e7449a6e-5323-4798-a9aa-5ac9d9ad1dc6.png">

In case we want to switch it off, it is as simple as:

```yaml
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
```

Here: https://github.com/python/typeshed/blob/master/.github/workflows/tests.yml#L5
I can send a PR if needed 🙂
